const express = require('express');
const dotenv = require('dotenv');
const authRoutes = require('./routes/authRoutes');
const brandsRoutes = require('./routes/brandsRoutes');
const productRoutes = require('./routes/productRoutes');
const categoriesRoutes = require('./routes/categoriesRoutes');
const cartItemRoutes = require('./routes/cartItemRoutes');
const wishlistItemsRoutes = require('./routes/wishlistItemsRoutes');
const orderRoutes = require('./routes/orderRoutes');
const reviewsRoutes = require('./routes/reviewRoutes');
const uploader = require('./routes/uploaderRoutes');
const authenticate = require('./middleware/authMiddleware.js');
const cookieParser = require('cookie-parser');
dotenv.config();

const app = express();
app.use(express.json());
app.use(cookieParser());
app.use('/api/auth', authRoutes);
app.use('/api/product',authenticate, productRoutes);
app.use('/api/brands',authenticate, brandsRoutes);
app.use('/api/categories', authenticate,categoriesRoutes);
app.use('/api/cartItem', authenticate,cartItemRoutes);
app.use('/api/wishlistItems', authenticate, wishlistItemsRoutes);
app.use('/api/order',authenticate, orderRoutes);
app.use('/api/review', authenticate,reviewsRoutes);
app.use('/api/upload', authenticate, uploader);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
